In [1]:
import pandas as pd

In [11]:
customer_df = pd.read_csv("./data/customer_churn.csv")

customer_df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
customer_df.shape

(7043, 21)

In [4]:
customer_df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [5]:
customer_df["Churn"].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [13]:
customer_df.columns = customer_df.columns.str.lower()

customer_df.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-VHVEG,0,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,1,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,1,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,1,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,0,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [14]:
customer_df["gender"] = customer_df["gender"].apply(lambda x: 1 if x == 'Male' else 0)

binary_cols = ["partner", "dependents", "onlinebackup", "churn","phoneservice","onlinesecurity", "deviceprotection", "techsupport", "streamingtv", "streamingmovies", "paperlessbilling"]

for col in binary_cols:
    customer_df[col] = customer_df[col].apply(lambda x: 1 if x == "Yes" else 0)


customer_df.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-VHVEG,0,0,1,0,1,0,No phone service,DSL,0,...,0,0,0,0,Month-to-month,1,Electronic check,29.85,29.85,0
1,5575-GNVDE,0,0,0,0,34,1,No,DSL,1,...,1,0,0,0,One year,0,Mailed check,56.95,1889.5,0
2,3668-QPYBK,0,0,0,0,2,1,No,DSL,1,...,0,0,0,0,Month-to-month,1,Mailed check,53.85,108.15,1
3,7795-CFOCW,0,0,0,0,45,0,No phone service,DSL,1,...,1,1,0,0,One year,0,Bank transfer (automatic),42.30,1840.75,0
4,9237-HQITU,0,0,0,0,2,1,No,Fiber optic,0,...,0,0,0,0,Month-to-month,1,Electronic check,70.70,151.65,1

In [16]:
customer_df["multiplelines"] = customer_df["monthlycharges"].apply(lambda x: 1 if x == "Yes" else 0)

customer_df

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-VHVEG,0,0,1,0,1,0,0,DSL,0,...,0,0,0,0,Month-to-month,1,Electronic check,29.85,29.85,0
1,5575-GNVDE,0,0,0,0,34,1,0,DSL,1,...,1,0,0,0,One year,0,Mailed check,56.95,1889.5,0
2,3668-QPYBK,0,0,0,0,2,1,0,DSL,1,...,0,0,0,0,Month-to-month,1,Mailed check,53.85,108.15,1
3,7795-CFOCW,0,0,0,0,45,0,0,DSL,1,...,1,1,0,0,One year,0,Bank transfer (automatic),42.30,1840.75,0
4,9237-HQITU,0,0,0,0,2,1,0,Fiber optic,0,...,0,0,0,0,Month-to-month,1,Electronic check,70.70,151.65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,0,0,1,1,24,1,0,DSL,1,...,1,1,1,1,One year,1,Mailed check,84.80,1990.5,0
7039,2234-XADUH,0,0,1,1,72,1,0,Fiber optic,0,...,1,0,1,1,One year,1,Credit card (automatic),103.20,7362.9,0
7040,4801-JZAZL,0,0,1,1,11,0,0,DSL,1,...,0,0,0,0,Month-to-month,1,Electronic check,29.60,346.45,0
7041,8361-LTMKD,0,1,1,0,4,1,0,Fiber optic,0,...,0,0,0,0,Month-to-month,1,Mailed check,74.40,306.6,1
7042,3186-AJIEK,0,0,0,0,66,1,0,Fiber optic,1,...,1,1,1,1,Two year,1,Bank transfer (automatic),105.65,6844.5,0

In [21]:
customer_df["contract"].unique()

customer_df["contract"] = customer_df["contract"].apply(lambda x: 31 if x == 'Month-to-month' else 365 if x == 'One year' else 365*2 if x == 'Two year' else x)

customer_df.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-VHVEG,0,0,1,0,1,0,0,DSL,0,...,0,0,0,0,31,1,Electronic check,29.85,29.85,0
1,5575-GNVDE,0,0,0,0,34,1,0,DSL,1,...,1,0,0,0,365,0,Mailed check,56.95,1889.5,0
2,3668-QPYBK,0,0,0,0,2,1,0,DSL,1,...,0,0,0,0,31,1,Mailed check,53.85,108.15,1
3,7795-CFOCW,0,0,0,0,45,0,0,DSL,1,...,1,1,0,0,365,0,Bank transfer (automatic),42.30,1840.75,0
4,9237-HQITU,0,0,0,0,2,1,0,Fiber optic,0,...,0,0,0,0,31,1,Electronic check,70.70,151.65,1

In [23]:
string_cols = customer_df.select_dtypes(include="object")

customer_df["internetservice"].unique()

array(['DSL', 'Fiber optic', 'No'], dtype=object)

In [24]:
customer_df["internetservice"] = customer_df["internetservice"].apply(lambda x: 1 if x == 'DSL' else 2 if x == 'Fiber optic' else 0)

customer_df.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-VHVEG,0,0,1,0,1,0,0,1,0,...,0,0,0,0,31,1,Electronic check,29.85,29.85,0
1,5575-GNVDE,0,0,0,0,34,1,0,1,1,...,1,0,0,0,365,0,Mailed check,56.95,1889.5,0
2,3668-QPYBK,0,0,0,0,2,1,0,1,1,...,0,0,0,0,31,1,Mailed check,53.85,108.15,1
3,7795-CFOCW,0,0,0,0,45,0,0,1,1,...,1,1,0,0,365,0,Bank transfer (automatic),42.30,1840.75,0
4,9237-HQITU,0,0,0,0,2,1,0,2,0,...,0,0,0,0,31,1,Electronic check,70.70,151.65,1

In [26]:
customer_df["paymentmethod"].unique()

array(['Electronic check', 'Mailed check', 'Bank transfer (automatic)',
       'Credit card (automatic)'], dtype=object)

In [27]:
customer_df["paymentmethod"] = customer_df["paymentmethod"].apply(lambda x: 1 if x == 'Electronic check' else 2 if x == 'Mailed check' else 3 if x == 'Bank transfer (automatic)' else 4)

customer_df.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-VHVEG,0,0,1,0,1,0,0,1,0,...,0,0,0,0,31,1,1,29.85,29.85,0
1,5575-GNVDE,0,0,0,0,34,1,0,1,1,...,1,0,0,0,365,0,2,56.95,1889.5,0
2,3668-QPYBK,0,0,0,0,2,1,0,1,1,...,0,0,0,0,31,1,2,53.85,108.15,1
3,7795-CFOCW,0,0,0,0,45,0,0,1,1,...,1,1,0,0,365,0,3,42.30,1840.75,0
4,9237-HQITU,0,0,0,0,2,1,0,2,0,...,0,0,0,0,31,1,1,70.70,151.65,1

In [31]:
customer_df["totalcharges"] = customer_df["totalcharges"].str.replace(' ', '0').astype(float)

customer_df.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-VHVEG,0,0,1,0,1,0,0,1,0,...,0,0,0,0,31,1,1,29.85,29.85,0
1,5575-GNVDE,0,0,0,0,34,1,0,1,1,...,1,0,0,0,365,0,2,56.95,1889.50,0
2,3668-QPYBK,0,0,0,0,2,1,0,1,1,...,0,0,0,0,31,1,2,53.85,108.15,1
3,7795-CFOCW,0,0,0,0,45,0,0,1,1,...,1,1,0,0,365,0,3,42.30,1840.75,0
4,9237-HQITU,0,0,0,0,2,1,0,2,0,...,0,0,0,0,31,1,1,70.70,151.65,1

In [35]:
customer_df.describe().T

,count,mean,std,min,25%,50%,75%,max
gender,7043.0,0.000000,0.000000,0.00,0.00,0.00,0.00,0.00
seniorcitizen,7043.0,0.162147,0.368612,0.00,0.00,0.00,0.00,1.00
partner,7043.0,0.483033,0.499748,0.00,0.00,0.00,1.00,1.00
dependents,7043.0,0.299588,0.458110,0.00,0.00,0.00,1.00,1.00
tenure,7043.0,32.371149,24.559481,0.00,9.00,29.00,55.00,72.00
phoneservice,7043.0,0.903166,0.295752,0.00,1.00,1.00,1.00,1.00
multiplelines,7043.0,0.000000,0.000000,0.00,0.00,0.00,0.00,0.00
internetservice,7043.0,1.222916,0.778877,0.00,1.00,1.00,2.00,2.00
onlinesecurity,7043.0,0.286668,0.452237,0.00,0.00,0.00,1.00,1.00
onlinebackup,7043.0,0.344881,0.475363,0.00,0.00,0.00,1.00,1.00
deviceprotection,7043.0,0.343888,0.475038,0.00,0.00,0.00,1.00,1.00
techsupport,7043.0,0.290217,0.453895,0.00,0.00,0.00,1.00,1.00
streamingtv,7043.0,0.384353,0.486477,0.00,0.00,0.00,1.00,1.00
streamingmovies,7043.0,0.387903,0.487307,0.00,0.00,0.00,1.00,1.00
contract,7043.0,269.078518,290.259782,31.00,31.00,31.00,365.00,730.00
paperlessbilling,7043.0,0.592219,0.491457,0.00,0.00,1.00,1.00,1.00
paymentmethod,7043.0,2.315633,1.148907,1.00,1.00,2.00,3.00,4.00
monthlycharges,7043.0,64.761692,30.090047,18.25,35.50,70.35,89.85,118.75
totalcharges,7043.0,2279.734304,2266.794470,0.00,398.55,1394.55,3786.60,8684.80
churn,7043.0,0.265370,0.441561,0.00,0.00,0.00,1.00,1.00

In [38]:
customer_df.corr(numeric_only=True)["churn"]

gender                   NaN
seniorcitizen       0.150889
partner            -0.150448
dependents         -0.164221
tenure             -0.352229
phoneservice        0.011942
multiplelines            NaN
internetservice     0.316846
onlinesecurity     -0.171226
onlinebackup       -0.082255
deviceprotection   -0.066160
techsupport        -0.164674
streamingtv         0.063228
streamingmovies     0.061382
contract           -0.394405
paperlessbilling    0.191825
paymentmethod      -0.262818
monthlycharges      0.193356
totalcharges       -0.198324
churn               1.000000
Name: churn, dtype: float64

In [44]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

scaler = StandardScaler()

smote = SMOTE(random_state=42)

X_scal = scaler.fit_transform(customer_df.drop(["customerid","churn"], axis=1))
y_scal = customer_df["churn"]

X, y = smote.fit_resample(X_scal,y_scal)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [45]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix, recall_score

model = RandomForestClassifier(random_state=42)

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Accuracy: ", accuracy_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred))
print("Recall: ", recall_score(y_test, y_pred))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy:  0.8554310011596443
Precision:  0.8479087452471483
Recall:  0.8650116369278511
Confusion matrix:
 [[1098  200]
 [ 174 1115]]